stages:
  - build
  - deploy

variables:
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_SHA}
  POPULATOR_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/populator:${CI_COMMIT_SHA}

.docker_build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  only:
    - master
  tags:
    - dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_app:
  extends: .docker_build
  script: 
    - docker build -t $IMAGE_NAME -f Dockerfile .
    - docker push $IMAGE_NAME

build_populator:
  extends: .docker_build
  script: 
    - docker build -t $POPULATOR_IMAGE_NAME -f populator/Dockerfile .
    - docker push $POPULATOR_IMAGE_NAME

deploy_production:
  stage: deploy
  image: $KUSTOMIZE_IMAGE
  only:
    - master
  tags:
    - docker
  script: 
    - cd .ci/kustomize
    - kustomize create --resources base
    - kustomize edit set image appImage=${IMAGE_NAME}
    - kustomize edit set image populatorImage=${POPULATOR_IMAGE_NAME}
    - kustomize edit set namespace $NAMESPACE_NAME
    - kustomize build . | kubectl --kubeconfig=${KUBE_CONFIG_FILE} apply -f -
    - kustomize build . | kubectl --kubeconfig=${KUBE_CONFIG_FILE} apply --dry-run -f - | grep deployment | awk '{print $1}' | xargs -n1 kubectl --kubeconfig=${KUBE_CONFIG_FILE} -n $NAMESPACE_NAME rollout status -w
  environment:
    name: prod 
    url: docs.ukfast.co.uk