apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-deployment.yaml
- app-service.yaml
- app-ingress.yaml
- app-job.yaml
- elasticsearch-deployment.yaml
- elasticsearch-service.yaml
