apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - path: app-ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: app-ingress
patchesStrategicMerge:
  - app-ingress.yaml
  - app-deployment.yaml
